on:
  schedule:
    - cron: '35 19 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes
      run: |
        echo "Daily commit" >> daily_commit.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Daily commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify 22f2001532@ds.study.iitm.ac.in
      run: echo "Daily commit made"
